### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by HWKim-postech**
## Marking lists
- [x] I have read the [Contributing Guidelines](https://github.com/SmartThingsCommunity/st-device-sdk-c/blob/master/CONTRIBUTING.md).
- [x] I have read the [Samsung Individual CLA](https://github.com/SmartThingsCommunity/st-device-sdk-c/blob/master/doc/SAMSUNGCLA.docx) and agree with it
     * We (SmartThings Device SDK team) may ask you to sign it for larger changes. In this case, once we receive it, we'll be able to accept your pull requests according to relevant laws.

- I submitted this PR against the correct branch:
  - [x] This pull-request is based on the latest [develop](https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/tree/develop) branch.
  - [x] I have ensured local tests pass about my code changes.

## License

Your contribution will be licensed under the [Apache License Ver2.0](https://github.com/SmartThingsCommunity/st-device-sdk-c-ref/blob/master/LICENSE).

### CODE REVIEW

**Review by stdk-scm — DISMISSED** [review]
LGTM

**Review by hdlee27 — DISMISSED** [review]
looks good to me

**Review by YongsulOh — CHANGES_REQUESTED** [review]
Dear developer

Thanks for your effort for our STDK

But current your patch-set has some personal related information such as onboarding_config.json & device_info.json

Could you please change them all same as previous sample style ?

**Comment by HWKim-postech** [comment]
Thank you for your careful review of my code.

I just changed my onboarding_config.json & device_info.json as your mentions.

Sorry for the late response.

Thank you.

**Pull request closed without merging**
